name: My Pi Image
on:  
  push:    
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: faddat/imager@v1
    - name: Shrink The Device Image
      run: sudo pishrink.sh -a -Z -v ubuntu-20.04.img
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Your Pi Image
        path: ubuntu-20.04.img.xz